#server:
#  port: 8187
#  servlet:
#    context-path: /market-auth
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.99.100:5433/postgres?currentSchema=auth
#    username: postgres
#    password: postgres
#  zipkin:
#    base-url: http://192.168.99.100:9411/
#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  application:
#    name: auth-service
#kafka:
#  server: "192.168.99.100:9092"
#  producer: "auth-service"
#redis:
#  host: "192.168.99.100"
#  port: 6380
#utils:
#  username:
#    prefix: "auth-service"
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#      fetchRegistry: false