#server:
#  port: 5555
#
#spring:
#  application:
#    name: gateway-service
#  zipkin:
#    base-url: http://192.168.99.100:9411/
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
#      routes:
#        - id: core-service-get-anything-order
#          uri: lb://core-service
#          predicates:
#            - Path=/core/api/v1/orders/{segment}
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-core
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#        - id: core-service-orders-another
#          uri: lb://core-service
#          predicates:
#            - Path=/core/api/v1/orders/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-core
#            - JwtAuthFilter
#            - NeedAuthenticationFilter
#        - id: core-service-paypal
#          uri: lb://core-service
#          predicates:
#            - Path=/core/api/v1/paypal/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-core
#            - JwtAuthFilter
#            - NeedAuthenticationFilter
#        - id: core-service-products
#          uri: lb://core-service
#          predicates:
#            - Path=/core/api/v1/products/**
#            - Method=DELETE,POST
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-core
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#        - id: core-service-another
#          uri: lb://core-service
#          predicates:
#            - Path=/core/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-core
#            - JwtAuthFilter
#        - id: cart-service
#          uri: lb://cart-service
#          predicates:
#            - Path=/cart/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-cart
#            - JwtAuthFilter
#        - id: auth-service-account-subscribers
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/api/v1/account/subscribers
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-auth
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#        - id: auth-service-account
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/api/v1/account/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-auth
#            - JwtAuthFilter
#            - NeedAuthenticationFilter
#        - id: auth-service-account
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/api/v1/registration/confirm-email
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-auth
#            - JwtAuthFilter
#            - NeedAuthenticationFilter
#        - id: auth-service-another
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-auth
#            - JwtAuthFilter
#        - id: analytics-service-yesterday
#          uri: lb://analytics-service
#          predicates:
#            - Path=/analytics/api/v1/analytical/product-quantity-rating-yesterday
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-analytics
#            - JwtAuthFilter
#        - id: analytics-service
#          uri: lb://analytics-service
#          predicates:
#            - Path=/analytics/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-analytics
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#        - id: promotion-service
#          uri: lb://promotion-service
#          predicates:
#            - Path=/promotion/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-promotion
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#        - id: messaging-service
#          uri: lb://messaging-service
#          predicates:
#            - Path=/messaging/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-messaging
#            - JwtAuthFilter
#            - NeedAdminRoleFilter
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#      fetchRegistry: false
#
#jwt:
#  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g