#server:
#  port: 8190
#  servlet:
#    context-path: /market-cart
#integrations:
#  product-service:
#    url: http://core-service/market-core/
#    connect-timeout: 500
#    read-timeout: 10000
#    write-timeout: 5000
#redis:
#  host: "192.168.99.100"
#  port: 6380
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#      fetchRegistry: false
#spring:
#  application:
#    name: cart-service
#  zipkin:
#    base-url: http://192.168.99.100:9411/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"