server:
  port: 8185
  servlet:
    context-path: /market-analytics
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: analytics-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-test.yaml
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: "analytical.broker"
integrations:
  core-service:
    url: http://192.168.99.100:8180
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
  auth-service:
    url: http://192.168.99.100:8180
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
eureka:
  client:
    enabled: false
redis:
  host: "localhost"
  port: 6380